version: "3.8"
services:
    backend:
      container_name: backend
      build:
        context: ./
        dockerfile: Dockerfile
      image: iluvcoffee
      ports:
        - "5000:5000"
      volumes:
        - ./:/app
    dbm:
      image: mongo # container image to be used
      restart: always 
      ports: # expose ports in “host:container” format
        - 27017:27017
      environment: #env variables to pass into the container
        MONGODB_DATABASE: nest-course
