version: "3.8"
services:
    backend:
      container_name: backend
      build:
        context: ./
        dockerfile: Dockerfile
      image: iluvcoffee
      ports:
        - "5000:5000"
      volumes:
        - ./:/app
      depends_on:
        - db
    db:
      container_name: db
      image:  postgres
      restart: always 
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: pass123
